name: mportal3_drift
description: Drift (ex. Moor) implementation for mp3 client.
version: 0.0.1
publish_to: 'none'
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  drift: ^1.5.0
  sqlite3_flutter_libs: ^0.5.5
  path_provider: ^2.0.9
  path: ^1.8.0
  crypto: ^3.0.2
  mportal3_core:
    path: ../mportal3_core

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.1.8
  drift_dev: ^1.5.2
