name: mportal3_rbs_api
description: Mp3 backend api implementation.
version: 0.0.1
publish_to: 'none'
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  mportal3_core:
    path: ../mportal3_core
  freezed_annotation: ^2.0.3
  json_serializable: ^6.1.5
  intl: ^0.17.0
  commons:
    path: ../commons

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  freezed: ^2.0.3
  build_runner: ^2.1.8
