name: mportal3_client_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  freezed_annotation: ^2.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.1.8
  freezed: ^2.0.3
